<div id="footer">
    <div class="container footer-container">
      <div class="row-fluid">
        <div class="span4 footermenu">  
            <h4>Browse</h4>
            <div class="footermenu">
                <ul>
                    <li><a href="http://www.clpress.com">Home</a></li>
                    <li><a href="http://www.clpress.com/publications">Books</a></li>
                    <li><a href="http://www.clpress.com/authors" title="CLP Authors">Authors</a></li>
                    <li><a href="http://www.clpress.com/about/home" title="About CLP">About</a></li>
                    <li class="leaf facebook"><a href="http://www.facebook.com/clpress" title="">Facebook</a></li>
                    <li class="leaf twitter"><a href="http://www.twitter.com/clibpress" title="">Twitter</a></li>
                    <li class="last leaf sign-up"><a href="http://www.clpress.com/about/signup" title="">Sign Up</a></li>
                </ul>
            </div>
        </div>
        <div class="span4">
            <h4>Subscribe To Us</h4>
            <p>
                <a href="http://www.clpress.com/about/signup">Sign Up For Mailings</a><br />
                <a href="http://www.clpress.com/rss.xml">News &amp; Press Releases RSS Feed</a><br />
                <a href="http://blog.acton.org/feed">Acton PowerBlog RSS Feed</a>
            </p>
            <h4>Other Acton Institute Resources</h4>
            <p>
                <a href="http://www.acton.org">Acton Institute Home Page</a><br />
                <a href="http://blog.acton.org">Acton PowerBlog</a>
            </p>
        </div>
        <div class="span4">
            <h4>Get In Touch</h4>
            <p>
                <a href="http://www.clpress.com/contact">Contact Online</a>
            </p>
            <address>
                <a href="http://www.clpress.com"><strong>Christian’s Library Press</strong></a><br />
                    98 E. Fulton Street<br />
                    Grand Rapids, MI 49503<br />
                    Phone: (616) 454-3080
            </address>
        </div>
        <div class="span12">  
            <div class="footer-bottom">
                &nbsp;
            </div>
        </div>
      </div>
    </div>
</div> <!-- /footer -->