<div class="row-fluid" id="header">
    <div class="span4 logo">
      <a href="http://www.clpress.com" title="Christian's Library Press" rel="home" id="logo">
        <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
      </a>
    </div>
<div class="span8 headercontent">
    <div class="headertop clearfix">
        <?php echo $this->getChildHtml('topBar') ?>
    </div>
    <div class="headermenu">
        <ul id="primary">
            <li class="first"><a href="http://www.clpress.com">Home</a></li>
            <li><a href="http://www.clpress.com/publications">Books</a></li>
            <li><a href="http://www.clpress.com/authors">Authors</a></li>
            <li class="last"><a href="http://www.clpress.com/about/home">About</a></li>
        </ul>
    </div>
    <div class="headersecondmenu">
        <div class="menu-block-wrapper menu-block-1 menu-name-menu-social-menu parent-mlid-0 menu-level-1">
            <ul class="menu">
                <li class="first facebook"><a href="http://www.facebook.com/clpress" title="">Facebook</a></li>
                <li class="leaf twitter"><a href="http://www.twitter.com/clibpress" title="">Twitter</a></li>
                <li class="last leaf sign-up"><a href="/about/signup" title="">Sign Up</a></li>
            </ul>
        </div>
    </div>
</div>
</div>

<div class="row-fluid">
    <div class="span12 slogan">
            <p>Providing resources on family &amp; marriage, culture &amp; work, church &amp; ministry, government &amp; law</p>
    </div>
</div>

<div class="row-fluid">
    <div class="span12 magento-menu-container">
            <?php echo $this->getChildHtml('topContainer'); ?>
            
        <div class="headermagentomenu">
            <?php echo $this->getChildHtml('store_language') ?>
            <p class="welcome-msg"><?php echo $this->getWelcome()?></p>
            <?php echo $this->getChildHtml('topLinks') ?>
        </div>
    </div>
</div>

<?php if($this->getChildHtml('breadcrumbs')){ ?>
<div class="row-fluid">
    <div class="span12 breadcrumb-container">
        <div class="breadcrumb">
            <?php echo $this->getChildHtml('breadcrumbs') ?>
        </div>
    </div>
</div>
<?php } ?>